# 모두를 위한 딥러닝 시즌 2 with PyTorch - Lab 01 : Tensor Manipulation
## 실습

## imports

In [1]:
import numpy as np
import torch

### 1D array with numpy

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

[0. 1. 2. 3. 4. 5. 6.]
Rank  of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 1D array with pytorch

In [7]:
t = torch.tensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape

print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D array with numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


### 2D array with pytorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [12]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

# 벡터에 스칼라가 분배되어 더해짐

tensor([[4., 5.]])


In [15]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

# [[1,2],[1,2]]가 되고, [[3,3],[4,4]]가 되어서 더해지게 된다. 쉽게 다가오지는 않는다.

tensor([[4., 5.],
        [5., 6.]])


In [16]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### 원래 matrix는 같은 사이즈끼리 행렬 연산이 되는데 pytorch.tensor에서는 에러 없이 위처럼 결과를 내니 주의
---------------------------------------------------------------------------------------------------------------------

### Mean, Sum, Max, Argmax

In [19]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [20]:
# Can't use mean() on integers 정수형은 mean()함수 불가
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [21]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


--------------------------------------------------------------------------------------------------------

In [24]:
# sum 함수
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


--------------------------------------------------------------------------------------------------------

In [28]:
# Max, Argmax 함수
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max()) # Returns one value: max

print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1]) # argmax는 인덱스 값이 리턴됨


print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#### 넘파이에서는 axis를 쓰지만 텐서에서는 dim을 쓰는데 dim=0 -> 열을 기준으로, dim=1 -> 행을 기준으로 씀을 알 수있다.(넘파이와 반대)
-----------------------------------------------------------------------------------------------------------------------------------

### View(=넘파이의 reshape)

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [30]:
print(ft.view([-1, 3]))        #  행은 상관없으니(-1) 열을 3개인 형태로(3) reshape하고싶다.
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [31]:
print(ft.view([-1, 1, 3]))      # tensor는 상관없으니 1행 3열로 reshape 하고싶다.
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [33]:
 ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


print(ft.squeeze())
print(ft.squeeze().shape)

print(ft.squeeze(dim=1)) # 토치 사이즈가 [3,1]이므로 dim =1을 넣어주면 같은 결과

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])


#### dimension이 1이면, 없애준다. (dim을 넣어서 지정 가능)
-------------------------------------------------------------------------------------------------------------------------------------

### Unsqueeze 

In [34]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [35]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [36]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape) # view(reshape)함수로도 가능함

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [38]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### squezee와는 반대로 지정한 dimension에 1을 넣어준다.
-------------------------------------------------------------------------------------------------------------------------------------

### Scatter(for one-hor encoding) 

In [39]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [40]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

# 원핫 인코딩할 떄 쓸 수 있는 함수

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Type Casting 

In [41]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [42]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [44]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [46]:
print(bt.long())
print(bt.float())

# 텐서의 타입들을 이렇게 바꿔줄 수 있음

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate 

In [47]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [49]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

# 이것도 마찬가지로 dim 옵션으로 어떻게 concat 할 것인지 정할 수 있음

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking 

In [50]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [51]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


#### concat을 좀 더 편리하게 이용할 수 있는 함수 여러개를 한 번에 묶을 수 있음
-------------------------------------------------------------------------------------------------------------------------------------

### Ones and Zeros Like

In [53]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [54]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

# 1이나 0으로 유니폼 분포를 만들 수 있음

# 이렇게하면 같은 device에서 연산이 된다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation 

In [55]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [56]:
print(x.mul(2.))  
print(x)
print(x.mul_(2.)) # 기존 tensor에 바로 곱해줘서 memory를 할당하지 않음
print(x)


tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Zip

In [57]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [58]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


#### tensor가 아닌 일반 배열로 선언 되는 것 같음 